
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/data_loader.ipynb

from fastai import datasets
import pickle, gzip
from torch import tensor

urls = {"MNIST_URL" : 'http://deeplearning.net/data/mnist/mnist.pkl'}

url = urls["MNIST_URL"]
def get_data():
    path = datasets.download_data(url, ext='.gz')
    with gzip.open(path, 'rb') as f:
        ((x_train, y_train), (x_valid, y_valid), _) = pickle.load(f, encoding='latin-1')
    return map(tensor, (x_train,y_train,x_valid,y_valid))