
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: docs/api_fit.ipynb

def fit(epochs, learn):
    for epoch in range(epochs):
        for xb, yb in learn.data.train_dl:
            loss = learn.model(xb, yb)
            learn.model.backward(yb)
            learn.opt.step()
            learn.opt.zero_grad()
        total_accuracy,total_loss = 0., 0.
        for xb, yb in learn.data.valid_dl:
            pred = learn.model.forward(xb)
            total_accuracy+=learn.model.loss.accuracy(pred, yb)*len(xb)
        print(epoch, round(total_accuracy/len(learn.data.valid_dl), 5))