
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: docs/api_optimizer.ipynb

import torch

class Optimizer():
    def __init__(self, parameters, lr=0.5): self.parameters,self.lr=list(parameters),lr

    def step(self):
        for parameter in self.parameters:
            parameter-=self.lr*parameter.g

    def zero_grad(self):
        for p in self.parameters: p.g = torch.zeros(p.shape)