
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: docs/nn_mse.ipynb

import sys
from pathlib import Path
sys.path.append(Path.cwd().parent.as_posix())
from nn.neural import Neural

class Mse(Neural):
    def __repr__(self): return "MSE()"
    def forward (self, inp, targ): return (inp.squeeze() - targ).pow(2).mean()
    def bwd(self, out, inp, targ): inp.g = 2*(inp.squeeze()-targ).unsqueeze(-1) / targ.shape[0]