
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/nn_neural.ipynb

class Neural():
    def __call__(self, *args):
        self.args = args
        self.out = self.forward(*args)
        return self.out

    def __repr__(self): raise Exception("__repr__ not implemented")
    def forward(self): raise Exception('forward propagation not implemented')
    def backward(self): self.bwd(self.out, *self.args)
    def parameters(self): return []